#!/bin/sh

mkdir -pv ~/.config/amfora/config.toml
ln -v -v ~/dotfiles/amfora/config.toml ~/.config/amfora/config.toml

mkdir -pv ~/.config/dunst/dunstrc
ln -v ~/dotfiles/dunst/dunstrc ~/.config/dunst/dunstrc

mkdir -pv ~/.config/htop/htoprc
ln -v ~/dotfiles/htop/htoprc ~/.config/htop/htoprc

mkdir -pv ~/.config/lf/lfrc
ln -v ~/dotfiles/lf/lfrc ~/.config/lf/lfrc

mkdir -pv ~/.config/neofetch/config.conf
ln -v ~/dotfiles/neofetch/config.conf ~/.config/neofetch/config.conf

mkdir -pv ~/.config/newsboat/config
ln -v ~/dotfiles/newsboat/config ~/.config/newsboat/config

mkdir -pv ~/.config/newsboat/urls
ln -v ~/dotfiles/newsboat/urls ~/.config/newsboat/urls

mkdir -pv ~/.config/nvim/init.vim
ln -v ~/dotfiles/nvim/init.vim ~/.config/nvim/init.vim

mkdir -pv ~/.config/picom/picom.conf
ln -v ~/dotfiles//picom/picom.conf ~/.config/picom/picom.conf

mkdir -pv ~/.config/qtile/config.py
ln -v ~/dotfiles//qtile/config.py ~/.config/qtile/config.py

mkdir -pv ~/.config/spotifyd/spotifyd.conf
ln -v ~/dotfiles//spotifyd/spotifyd.conf ~/.config/spotifyd/spotifyd.conf

mkdir -pv ~/.config/spotify-tui/config.yml
ln -v ~/dotfiles/spotify-tui/config.yml ~/.config/spotify-tui/config.yml

mkdir -pv ~/.config/tspreed/tspreed.rc
ln -v ~/dotfiles/tspreed/tspreed.rc ~/.config/tspreed/tspreed.rc

mkdir -pv ~/.config/x11/xinitrc
ln -v ~/dotfiles/x11/xinitrc ~/.config/x11/xinitrc

mkdir -pv ~/.config/zathura/zathurarc
ln -v ~/dotfiles/zathura/zathurarc ~/.config/zathura/zathurarc

mkdir -pv ~/.config/zsh/.zshenv
ln -v ~/dotfiles/zsh/.zshenv ~/.config/zsh/.zshenv

mkdir -pv ~/.config/zsh/.zshrc
ln -v ~/dotfiles/zsh/.zshrc ~/.config/zsh/.zshrc

ln -v ~/dotfiles/redshift.conf ~/.config/redshift.conf

doas ln -v ~/dotfiles/pacman.conf /etc/pacman.conf
doas ln -v ~/dotfiles/paru.conf /etc/paru.conf
doas ln -v ~/dotfiles/vconsole.conf /etc/vconsole.conf
