#!/bin/sh
thermometer=🌡️
while :; do
        vol=$(pamixer --get-volume-human)
        mem=$(free -h | awk '/^Mem/ { print $3 "/" $2 }')
        temp=$(sensors | awk '/Core 0/ {print $3}')
        bat=$(cat /sys/class/power_supply/BAT0/capacity)%
        date=$(date '+(%a) %d %b %y')
        time=$(date '+%H.%M.%S')
        xsetroot -name " 🔉 $vol | 🐏 $mem | $thermometer $temp | 🔋 $bat | $date | $time"
        sleep 1s
done
