#!/bin/sh

read -p "Which user's files are to be mugged? "  user &&

[ -z "$user" ] && exit 0

mkdir -p /home/$user/.config/amfora
ln /home/$user/dotfiles/amfora/config.toml /home/$user/.config/amfora/config.toml

mkdir -p /home/$user/.config/dunst
ln /home/$user/dotfiles/dunst/dunstrc /home/$user/.config/dunst/dunstrc

mkdir -p /home/$user/.config/fontconfig
ln /home/$user/dotfiles/fontconfig/fonts.conf /home/$user/.config/fontconfig/fonts.conf

mkdir -p /home/$user/.config/htop
ln /home/$user/dotfiles/htop/htoprc /home/$user/.config/htop/htoprc

mkdir -p /home/$user/.config/gtk-2.0
mkdir -p /home/$user/.config/gtk-3.0

mkdir -p /home/$user/.config/lf
ln /home/$user/dotfiles/lf/lfrc /home/$user/.config/lf/lfrc

mkdir -p /home/$user/.config/mpd
ln /home/$user/dotfiles/mpd/mpd.conf /home/$user/.config/mpd/mpd.conf

mkdir -p /home/$user/.config/msmtp

mkdir -p /home/$user/.config/mpv
ln /home/$user/dotfiles/mpv/mpv.conf /home/$user/.config/mpv/mpv.conf
ln /home/$user/dotfiles/mpv/input.conf /home/$user/.config/mpv/input.conf

mkdir -p /home/$user/.config/ncmpcpp
ln /home/$user/dotfiles/ncmpcpp/config /home/$user/.config/ncmpcpp/config
ln /home/$user/dotfiles/ncmpcpp/bindings /home/$user/.config/ncmpcpp/bindings

mkdir -p /home/$user/.config/neofetch
ln /home/$user/dotfiles/neofetch/config.conf /home/$user/.config/neofetch/config.conf

mkdir -p /home/$user/.config/newsboat
ln /home/$user/dotfiles/newsboat/config /home/$user/.config/newsboat/config
ln /home/$user/dotfiles/newsboat/urls /home/$user/.config/newsboat/urls

mkdir -p /home/$user/.config/nvim
ln /home/$user/dotfiles/nvim/init.vim /home/$user/.config/nvim/init.vim

mkdir -p /home/$user/.config/picom
ln /home/$user/dotfiles//picom/picom.conf /home/$user/.config/picom/picom.conf

mkdir -p /home/$user/.config/qtile
ln /home/$user/dotfiles//qtile/config.py /home/$user/.config/qtile/config.py

mkdir -p /home/$user/.config/spotifyd
ln /home/$user/dotfiles//spotifyd/spotifyd.conf /home/$user/.config/spotifyd/spotifyd.conf

mkdir -p /home/$user/.config/spotify-tui
ln /home/$user/dotfiles/spotify-tui/config.yml /home/$user/.config/spotify-tui/config.yml

mkdir -p /home/$user/.config/sxiv/exec
ln /home/$user/dotfiles/sxiv/exec/key-handler /home/$user/.config/sxiv/exec/key-handler

mkdir -p /home/$user/.config/tspreed
ln /home/$user/dotfiles/tspreed/tspreed.rc /home/$user/.config/tspreed/tspreed.rc

mkdir -p /home/$user/.config/x11
ln /home/$user/dotfiles/x11/xinitrc /home/$user/.config/x11/xinitrc

mkdir -p /etc/X11/xorg.conf.d
ln /home/$user/dotfiles/x11/00-mouse.conf /etc/X11/xorg.conf.d/00-mouse.conf
ln /home/$user/dotfiles/x11/20-intel.conf /etc/X11/xorg.conf.d//20-intel.conf
ln /home/$user/dotfiles/x11/30-touchpad.conf /etc/X11/xorg.conf.d/30-touchpad.conf

mkdir -p /home/$user/.config/zathura
ln /home/$user/dotfiles/zathura/zathurarc /home/$user/.config/zathura/zathurarc

mkdir -p /home/$user/.config/zsh
ln /home/$user/dotfiles/zsh/.zshenv /home/$user/.config/zsh/.zshenv
ln /home/$user/dotfiles/zsh/.zshrc /home/$user/.config/zsh/.zshrc
touch /etc/zsh/zshenv
echo "source /home/$user/.config/zsh/.zshenv" > /etc/zsh/zshenv
mkdir -p /home/$user/.cache/zsh
touch /home/$user/.cache/zsh/history

ln /home/$user/dotfiles/redshift.conf /home/$user/.config/redshift.conf

mkdir -p /home/$user/.config/git
touch /home/$user/.config/git/config

mkdir -p /home/$user/.config/wget
touch /home/$user/.config/wget/wgetrc

chown $user /home/$user -R
